apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calcom-stack-rnm
  namespace: argocd  # Ensure this is the namespace where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/Mershab99/calcom-helm.git
    targetRevision: removeProbes
    path: charts/calcom-stack
    helm:
      valuesObject:
        postgresql:
          auth:
            username: user
            password: password
            database: calcom
          primary:
            persistence:
              enabled: true
              storageClass: ceph-block
        calcom:
          replicaCount: 1
          image:
            tag: v3.7.11
          ingress:
            enabled: true
            className: "nginx"
            annotations: {}
              #nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
            hosts:
              - host: schedule.rnmsolutions.ca
                paths:
                  - path: /
                    pathType: Prefix
#                api:
#                  path: /api/(.*)
#                  pathType: ImplementationSpecific
  destination:
    name: loft-new-project-vcluster-rnm-cluster
    namespace: calcom-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calcom-stack-rnm-resources
  namespace: argocd  # Ensure this is the namespace where Argo CD is installed
spec:
  project: "default"
  source:
    repoURL: https://github.com/Mershab99/rnmsolutions.git
    targetRevision: "main" #Based on environment
    path: 'deploy/secrets/calcom/'
    directory:
      recurse: true
  destination:
    name: loft-new-project-vcluster-rnm-cluster
    namespace: calcom-stack
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

