apiVersion: v1
kind: Secret
metadata:
  name: calcom
stringData:
  DATABASE_URL: postgresql://user:password@calcom-stack-postgresql/calcom
  NEXT_PUBLIC_WEBAPP_URL: https://schedule.rnmsolutions.ca
  NEXT_PUBLIC_WEBSITE_URL: https://schedule.rnmsolutions.ca

  # It is highly recommended that the NEXTAUTH_SECRET must be overridden and very unique
  # Use `openssl rand -base64 32` to generate a key
  NEXTAUTH_SECRET: qvFDOm301WZH+hb6eqvJpbqSrmaeQSSMPFaqI9KBz1o=

  # Encryption key that will be used to encrypt CalDAV credentials, choose a random string, for example with `dd if=/dev/urandom bs=1K count=1 | md5sum`
  CALENDSO_ENCRYPTION_KEY: wqvUz+eWyqf8RBdxxDE+yEtAnUkcBAlSdp4+2l+tUB8=
 
  CALCOM_TELEMETRY_DISABLED: '1'
    #ALLOWED_HOSTNAMES: '["localhost:3000","https://schedule.rnmsolutions.ca/*"]'
  NEXTAUTH_URL: 'https://schedule.rnmsolutions.ca'
  NODE_TLS_REJECT_UNAUTHORIZED: '0' 
